theme: jekyll-theme-slate
title: ICASR
description: International Collaboration for the Automation of Systematic Reviews
github:
  is_project_page: false
# Google Analytics
google_analytics: UA-124820951-1

